-- Create notifications table
CREATE TABLE notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    type VARCHAR(30) NOT NULL CHECK (type IN ('order_created', 'order_updated')),
    title VARCHAR(255) NOT NULL,
    description TEXT,
    reference_id UUID,           -- order.id
    warehouse_id UUID REFERENCES warehouses(id) ON DELETE CASCADE,
    metadata JSONB DEFAULT '{}', -- order_number, old_status, new_status, etc.
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create notification_reads table (read state per user)
CREATE TABLE notification_reads (
    notification_id UUID NOT NULL REFERENCES notifications(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    read_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    PRIMARY KEY (notification_id, user_id)
);

-- Indexes
CREATE INDEX idx_notifications_warehouse_id ON notifications(warehouse_id);
CREATE INDEX idx_notifications_created_at ON notifications(created_at DESC);
CREATE INDEX idx_notifications_reference_id ON notifications(reference_id);
CREATE INDEX idx_notification_reads_user_id ON notification_reads(user_id);

-- Enable RLS
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification_reads ENABLE ROW LEVEL SECURITY;

-- RLS: admins see all notifications, managers see only their warehouses
CREATE POLICY "Admins and managers can view notifications" ON notifications
    FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM users u
            JOIN roles r ON u.role_id = r.id
            WHERE u.id = auth.uid()
            AND r.name = 'admin'
        )
        OR
        EXISTS (
            SELECT 1 FROM users u
            JOIN roles r ON u.role_id = r.id
            JOIN warehouse_users wu ON wu.user_id = u.id
            WHERE u.id = auth.uid()
            AND r.name = 'manager'
            AND wu.warehouse_id = notifications.warehouse_id
        )
    );

-- RLS: service role can insert notifications (via triggers)
CREATE POLICY "Service role can insert notifications" ON notifications
    FOR INSERT
    WITH CHECK (true);

-- RLS: users can read their own notification reads
CREATE POLICY "Users can read own notification reads" ON notification_reads
    FOR SELECT
    USING (user_id = auth.uid());

-- RLS: users can insert their own notification reads
CREATE POLICY "Users can insert own notification reads" ON notification_reads
    FOR INSERT
    WITH CHECK (user_id = auth.uid());

COMMENT ON TABLE notifications IS 'System notifications generated by order events';
COMMENT ON TABLE notification_reads IS 'Tracks which notifications each user has read';
COMMENT ON COLUMN notifications.metadata IS 'Extra data: order_number, old_status, new_status, status_label';
